#!/usr/bin/env expect

set KERNEL "./vmlinuz"
set INITRD "./initrd.gz"
set CMDLINE "earlyprintk=serial console=ttyS0"

exec rm -f disk.dmg
exec hdiutil create -megabytes 20 -fs "MS-DOS" disk
set DISK [exec hdiutil attach -nomount -noverify -noautofsck disk.dmg | head -n1 | cut -f1 -d " "]
set RDISK [string map { disk rdisk } $DISK]

spawn ../build/hyperkit -A -m 512M -s 0:0,hostbridge -s 31,lpc -l com1,stdio -s 1:0,ahci-hd,$RDISK -f kexec,$KERNEL,$INITRD,$CMDLINE
set pid [exp_pid]
set timeout 20

expect {
  timeout {puts "FAIL boot"; exec kill -9 $pid; exit 1}
  "\r\ntc@box:~$ "
}
send "sudo mount /dev/sda1 /mnt/sda1\r\n"
send "sudo touch /mnt/sda1/test\r\n"
send "sudo umount /mnt/sda1\r\n"
send "sync\r\n"
send "sudo halt\r\n";
expect {
  timeout {puts "FAIL shutdown"; exec kill -9 $pid; exit 1}
  "reboot: System halted"
}

expect {
  timeout {puts "FAIL process-exit"; exec kill -9 $pid; exit 1}
  eof
}
set status [wait]
puts "EXIT status:  $status"

exec hdiutil mount -mountpoint ./test-vol ${DISK}s1
exec cat ./test-vol/test
exec hdiutil detach $DISK

puts "\n\nPASS"
