package analysis

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
)

// IsFileGenerated returns true if the specified file is generated, or false if it's handcrafted.
// rootDir is the filepath of root directory, but name is a '/'-separated path to file.
func IsFileGenerated(rootDir, name string) (bool, error) {
	switch {
	case strings.HasPrefix(name, "Godeps/"):
		return true, nil
	default:
	}
	f, err := os.Open(filepath.Join(rootDir, filepath.FromSlash(name)))
	if err != nil {
		return false, err
	}
	defer f.Close()
	r := bufio.NewReader(f)
	s, err := r.ReadString('\n')
	if err != nil {
		return false, err
	}
	if s == "// Code generated by protoc-gen-gogo.\n" { // protoc-gen-gogo special case.
		return true, nil
	}
	return (strings.Contains(s, "GENERATED") || strings.Contains(s, "generated")) && strings.Contains(s, "DO NOT EDIT"), nil
}
