package analysis

import (
	"bufio"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// IsFileGenerated returns true if the specified file is generated, or false if it's handcrafted.
// rootDir is the filepath of root directory, but name is a '/'-separated path to file.
func IsFileGenerated(rootDir, name string) (bool, error) {
	// Detect from name.
	switch {
	case strings.HasPrefix(name, "vendor/") || strings.Contains(name, "/vendor/"):
		return true, nil
	case strings.HasPrefix(name, "Godeps/"):
		return true, nil
	}

	// Detect from file contents.
	f, err := os.Open(filepath.Join(rootDir, filepath.FromSlash(name)))
	if err != nil {
		return false, err
	}
	defer f.Close()
	r := bufio.NewReader(f)
	s, err := r.ReadString('\n')
	if err == io.EOF {
		// Empty file or exactly 1 line is not considered to be generated.
		return false, nil
	} else if err != nil {
		return false, err
	}
	if strings.Contains(s, "Code generated by") { // Consistent with https://golang.org/cl/15073.
		return true, nil
	}
	return (strings.Contains(s, "GENERATED") || strings.Contains(s, "generated")) && strings.Contains(s, "DO NOT EDIT"), nil
}
